### ISSUE TITLE
Docker containers get progressively bigger

### ISSUE THREAD

**Issue by ReverseControl** [FACT0RN/factoring#15]
It seems there is a bug where the containers size and memory usage increase over time to fill the hard drive and exhaust memory. To be investigated further: it seems logging text files are not deleted after each factorization and temporary files created inside the containers need to be examined to make sure we are deleting them when we are done using them. The memory usage seems to be a docker thing, not a yafu thing, so hopefully fixing the former problem will fix the memory problem.

@daedalus Can you look into this please?

**Comment by daedalus** [comment]
If yafu gets OOMkilled it will leave the dat files polluting the filesystem.
I just added a time out command before calling yafu to avoid consuming all the ram. Ex: `timeout -n 180 yafu ...`

**Comment by ReverseControl** [comment]
@daedalus The issue was the logging done in yafu. I removed the sessions log and the Quadratic SIeve log. The latter was taking 32MB per integer factored...that file is not needed for anything. See fix here: https://github.com/FACT0RN/factoring/commit/9a6aeb0643ed5e883653135f00e951e56673d6de.
