### ISSUE TITLE
how to fix his issue to factoring

### ISSUE THREAD

**Issue by moodsj** [FACT0RN/factoring#2]
when i exc 
RPC_USER=rpcuser RPC_PASS=verylongrpcpasswordpassword SCRIPTPUBKEY=avalidscriptpubkey python FACTOR.py

it error :

***   Warning: new maximum stack size = 536870912 (512.000 Mbytes).
Traceback (most recent call last):
  File "FACTOR.py", line 629, in <module>
    gHash = ctypes.CDLL("./gHash.so").gHash
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./gHash.so: cannot open shared object file: No such file or directory

**Comment by ReverseControl** [comment]
@moodsj Hey! Sorry, just saw this issue. Yes, you need to run the ``build.sh`` script to build that binary. It will put it in the right place and then you can run the python script.

**Comment by ReverseControl** [comment]
Closing. Re-open if you are still having this same issue.

**Comment by ReverseControl** [comment]
@moodsj , there is a dockerfile that does all this stuff now. Should be a lot easier to mine.
